INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('PICCA', 'P1', '1A');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('PICCA', 'P2', '1A');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('PICCA', 'P3', '1A');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('BOKKA', 'Q1', '1B');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('BOKKA', 'Q2', '1B');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('BOKKA', 'Q3', '1B');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('CENA', 'R1', '1C');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('CENA', 'R2', '1C');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('CENA', 'R3', '1C');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER) VALUES ('AB', 'BA', 'ab@123', '123/5', 'SL','WARA', '1234');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER) VALUES ('CD', 'DC', 'cd@456', '456/5', 'SL','WARA', '4567');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER) VALUES ('EF', 'FE', 'ef@789', '789/5', 'SL','WARA', '7890');

-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (1, 1, 100);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (1, 2, 101);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (1, 3, 102);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (2, 1, 103);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (2, 2, 104);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (2, 3, 105);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (3, 1, 106);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (3, 2, 100);
-- INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES (3, 3, 100);

